### ISSUE TITLE
Add Mirai, Sugarcane, Patina and more...

### ISSUE THREAD

**Issue by Lacosst0** [UeberallGebannt/server-softwares#17]
Patina - https://github.com/PatinaMC/Patina

Sugarcane - https://github.com/SugarcaneMC/Sugarcane
Mirai - https://github.com/etil2jz/Mirai
Yatopia, and this 2 ^^^ can be bad
Check https://kennytv.github.io/list-of-shame/ (kennytv list of shame) for more info

Other stuff 💀 - https://anythingmc.xyz/server/info/lists/server_software/ - Im too lazy to check everything in it
(github - https://github.com/Anything-Minecraft-Team/anything-minecraft/blob/main/docs/server/info/lists/server_software.md)
This found my friend, idk how, dont ask

**Comment by Lacosst0** [comment]
This project is really cool, keep it up! 
I would be very happy, if you will make plugin list, like anythingmc did with anti cheat list, but with more plugins that supported, and more categories like:

New content adders: Oraxen, ItemsAdder, Executableitems and so on
Anti-Cheat list: https://www.spigotmc.org/wiki/anti-cheat-list-bukkit-and-spigot/
Sync plugins: HyskSync...
Chat plugins: Chatty...

And yeah, please add useful links page: 
https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/
https://github.com/Incendo/awesome-minecraft
https://kennytv.github.io/list-of-shame/
Maybe docs for paper, purpur, pufferfish
Oh and something like that:
https://www.reddit.com/r/admincraft/comments/pbx5le/what_is_your_favorite_purpur_feature/

I really love this project, and I will post more stuff, to help it! 
Have a nice day! <3

**Comment by UeberallGebannt** [comment]
Hey, thanks for all the tips and information!

I saw Patina multiple times but was not able to get more information about it since the README/wiki isn't exactly helpfull. I create a fork chain for all projects and I cannot tell which patches are included in Patina.

SugarcaneMC doesn't even have builds yet, I doubt they will have some in the near future. There are a lot of red flags when it comes to that software (information on website and readme differ for example) but I will take a look as soon as there are downloads.

I'm unsure about Mirai, as even the dev says it is unstable and an experiment. I will most likely mark it as an experimental fork and add it still.
![grafik](https://user-images.githubusercontent.com/50475262/186086707-c41ca193-41fc-48d2-9739-92dbdff5f77b.png)
I mean, you even linked the list of shame for that one xD

All the other links will be added to the README soon:tm:!

**Comment by Lacosst0** [comment]
Patina is probably Purpur fork, with Yatopia, Empircecraft, Jettpack and Akrin patches (Patina/patches/server/ and Patina/patches/removed/server) (forgot about them - https://github.com/starlis/empirecraft, https://github.com/Akarin-project/Akarin, https://gitlab.com/Titaniumtown/JettPack)
And I also found Prismarine - https://github.com/PrismarineTeam/Prismarine and Slice - https://github.com/Cryptite/Slice in my own small archive

**Comment by UeberallGebannt** [comment]
Added all of these softwares (except the ones from AnythingMC) in 5e9daa1.
